### PLANTILLA
POST http://localhost:<PORT>/apiv1
Content-Type: application/json

{
    "nombre": "",
    "venta": ,
    "precio": ,
    "photo": "",
    "tags": [""]
}

### EJEMPLO
POST http://localhost:XXXX/apiv1
Content-Type: application/json

{
    "nombre": "Guitarra",
    "venta": false,
    "precio": 120,
    "photo": "guitarra.jpg",
    "tags": ["lifestyle", "work"]
}