POST http://localhost:3009/apiv1/authenticate
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "1234"
}

###
GET  http://localhost:3009/apiv1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWE0ZDY4MjMwMjExMDUxMGM3OGU5ODQiLCJpYXQiOjE2Mzg0NTgzOTgsImV4cCI6MTYzODYzMTE5OH0.S_E0aBVJKVjoWC35G5b62f2IanVClqqtjCoHcTij0PQ


